services:
  - type: web
    name: portfolio-ouassim
    runtime: static
    buildCommand: echo "No build required"
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
